### ISSUE TITLE
U5 / Part

### ISSUE THREAD

**Issue by MalteSch2000** [BlakeGarner/encoders-for-etc-eos#1]
Hey, I bought the parts by part number. Unfortunately the U5 doesn’t fit. The I think you mean the SN74HCT245DWR is too big. What component do you use?

I think you mean the SN74HCT245PWR instead of SN74HCT245DWR. 

Thank you. 

Best regards

**Comment by BlakeGarner** [comment]
Yup. You are right. Should be the SN74HCT245PWR part.
