### ISSUE TITLE
SVGs for laser cutting don’t match rev C PCB

### ISSUE THREAD

**Issue by cortices** [BlakeGarner/encoders-for-etc-eos#5]
I laser cut the acrylic parts but they seem to suit an earlier, narrower version with the encoders directly above each other instead of staggered. Is there a newer acrylic cut file?

**Comment by BlakeGarner** [comment]
Hi,
The master branch is still on the rev B PCB layout. If you want to use the newer rev C PCB layout, switch to the revC branch instead and you will find the updated acrylic SVG files. 

I probably had a good reason for not merging the master branch forward, but I forget what it was!

**Comment by cortices** [comment]
Whoops, thanks.
